### PR TITLE
Fix https://github.com/sunaku/dasht/issues/6

### PR DESCRIPTION
**Pull request by netei**
Fix https://github.com/sunaku/dasht/issues/6

### CODE REVIEW

**Comment by sunaku** [comment]
Thanks! :+1:   Unfortunately, I just found that the `&&` operator prevents failing exit statuses from aborting a script run under `set -e`, so instead we'll need to rearrange the expression again in terms of `||` as follows:

```sh
test "$have" = "$want" -o ! -e "$want" || mv "$want" "$have"
```

**Comment by sunaku** [comment]
Cherry-picked into master branch at commit 92fc97d42190915a45d9b25b3c732a19ec4fc42c. :bow:

**Comment by netei** [comment]
I would recommend avoiding `-o` and `-a` , because they can be some unwanted errors if for example "$have" is equal to "-e".

See this question for a case where it could happen : http://stackoverflow.com/questions/35578327/bash-too-many-arguments-greater-than-symbol#comment58844153_35578327 

It is recommended to use && and || instead of -a and -o .

See : 

> The XSI extensions specifying the -a and -o binary primaries and the '(' and ')' operators have been marked obsolescent. (Many expressions using them are ambiguously defined by the grammar depending on the specific expressions being evaluated.) Scripts using these expressions should be converted to the forms given below. Even though many implementations will continue to support these obsolescent forms, scripts should be extremely careful when dealing with user-supplied input that could be confused with these and other primaries and operators. Unless the application developer knows all the cases that produce input to the script, invocations like:
> 
> test "$1" -a "$2"
> 
> should be written as:
> 
> test "$1" && test "$2"
> 
> to avoid problems if a user supplied values such as $1 set to '!' and $2 set to the null string. That is, in cases where maximal portability is of concern, replace:
> 
> test expr1 -a expr2
> 
> with:
> 
> test expr1 && test expr2
> 
> and replace:
> 
> test expr1 -o expr2
> 
> with:
> 
> test expr1 || test expr2



http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

**Comment by sunaku** [comment]
Good point. :+1: However, that only seems to affect us when not enough syntax elements are presented to the `test` command.  For instance, `test "$have" =` by itself is definitely ambiguous (checks whether a file named "=" exists) whereas the overall `test "$have" = "$want"` expression behaves as intended:

```sh
$ dash -exc 'have="-e"; want="foo"; touch =; ls -l =; test "$have" =; test "$have" = "$want"'
+ have=-e
+ want=foo
+ touch =
+ ls -l =
-rw-r--r-- 1 sunny sunny 0 Mar 10 22:24 '='
+ test -e =
+ test -e = foo
exit 1
```

In fact, even when `$want` is undefined or an empty string, the double quotes that surround it cause it to be passed down as an empty string argument to the test(1) command's argv:

```sh
$ dash -exc 'have="-e"; want=; touch =; ls -l =; test "$have" =; test "$have" = "$want"'
+ have=-e
+ want=
+ touch =
+ ls -l =
-rw-r--r-- 1 sunny sunny 0 Mar 10 22:25 '='
+ test -e =
+ test -e =
exit 1
```

Anyway, I'll change the code if it _really_ bothers you the way it's currently implemented :hankey:, but I think there's no danger here because the overall syntax elements (looking at the entire argv) looks fine. :sweat_smile:

**Comment by netei** [comment]
I also think the current code is ok now, I think there's no way for test to misunderstand something here.
I'm used to prefer '&&' and '||' over '-a' and '-o' because sometimes, "-a" and "-o" can lead to ambiguities, but the other syntax is most of the time correct too.

**Pull request closed without merging**
